.TH "BRIGHTNESSCTL" "1" "2025-09-20" "brightnessctl" "brightnessctl"
. 
.SH "NAME"
brightnessctl \- read and control device brightness
.
.
.SH "SYNOPSIS"
\fBbrightnessctl\fR [\fBget\fR|\fBset\fR] [\fIOPTION\fR]... [\fIVALUE\fR]
.
.
.SH "DESCRIPTION"
.P
Controls and retrieves the brightness of various devices like backlights
or leds.
Depending on the compilation, it uses the dbus or writes to the
files in /sys/class directly, whereas the latter requires root to execute.
.
.
.SH "OPTIONS"
.SS "General"
.TP
.B \-p\fR, \fB\-\-pretend
do not perform write operation
.
.TP
.B \-m\fR, \fB\-\-machine-readable
produce machine readable output
.
.TP
.B \-d\fR, \fB\-\-device=\fIDEVICE
specify device name
.
.TP
.B \-c\fR, \fB\-\-class=\fICLASS
specify device class
.
.TP
.B \-h\fR, \fB\-\-help
print a help message
.
.TP
.B \-v\fR, \fB\-\-version
print version and exit
.
.TP
.B \-e\fR, \fB\-\-exponent\fR[\fB=\fIK\fR]
set exponent of brightnesscurve
.br
If the flag is not provided a linear curve is used (\fIK\fR=1).
If the flag is provided without any argument, \fIK\fR=4 is used.
.
.TP
.B \-q\fR, \fB\-\-quiet
suppress output
.br
This silences some error messages (but not error return codes) and
superflous messages for `get` and `set`.
.
.TP
.B \-s\fR, \fB\-\-save
save previous state in a temporary file
.
.
.SS "Set"
.P
The set operation sets the brightness of the device specified through
\fB\-\-device=\fIDEVICE\fR and \fB\-\-class=\fICLASS\fR.
In general, it expects a \fIVALUE\fR to be provided in one of the
following formats:
.
.TP
.I NN
where \fINN\fR is a non-negative integer
.br
This sets the brightness to the absolute value \fINN\fR.
.
.TP
.I NN\fB%
This sets the brightness to \fINN\fR% of the maximum brightness.
It will respect the \fB\-\-exponent\fR[\fB=\fIK\fR] setting.
The curve is:
.br
.I NN\fR%^\fIK\fR * MAXIMUM_BRIGHTNESS.
.
.TP
.B +\fINN\fR[\fB%\fR]
This increases the brightness by \fINN\fR[\fB%\fR].
.
.TP
.I NN\fR[\fB%\fR]\fB-
This decreases the brightness by \fINN\fR[\fB%\fR].
.
.P
The following are a list of options specific to the use with set.
.
.TP
.B \-n\fR, \fB\-\-min\-value=\fIn
set minimum brightness
.br
This overrides any value computation.
.
.TP
.B \-r\fR, \fB\-\-restore
restore previously saved state
.br
If this flag is set, providing a \fIVALUE\fR is not required as the
brightness will be restored from a previous call with \fB\-\-save\fR.
The two can be used together (after an initial save) to toggle between the
current and the previous state.
.
.SS "Get"
.P
The get operation retrieves the brightness of the specified device.
.
.TP
.B \-l\fR, \fB\-\-list
List info for all devices
.br
This is useful to get the class and name of a device if you don't know it.
.
.
.SH "EXIT STATUS"
.TP
0
everything is fine
.TP
1
an error occurred
.br
In some cases you will still get the output you wanted from this.
For example, if you do not (fully) specify the device you want to use,
the program will default to what is probably the backlight of your main
monitor.
When doing so it will also print a huge complaint about that if it is
not silenced with \fB\-\-quiet\fR.
